# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgentInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgentInfo.proto',
  package='AnimFireChalAgent',
  syntax='proto3',
  serialized_options=_b('\n\021AnimFireChalAgentB\021AnimFireChalProto'),
  serialized_pb=_b('\n\x0f\x41gentInfo.proto\x12\x11\x41nimFireChalAgent\"5\n\tAgentInfo\x12(\n\x06\x61gents\x18\x01 \x03(\x0b\x32\x18.AnimFireChalAgent.Agent\"8\n\nActionInfo\x12*\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x19.AnimFireChalAgent.Action\"X\n\x05\x41gent\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\r\n\x05water\x18\x04 \x01(\x05\x12\n\n\x02hp\x18\x05 \x01(\x05\x12\x0c\n\x04idle\x18\x06 \x01(\x05\"/\n\x06\x41\x63tion\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x62uilding_id\x18\x02 \x01(\x05\x32\x62\n\x11\x41nimFireChalAgent\x12M\n\x0cgetAgentInfo\x12\x1d.AnimFireChalAgent.ActionInfo\x1a\x1c.AnimFireChalAgent.AgentInfo\"\x00\x42&\n\x11\x41nimFireChalAgentB\x11\x41nimFireChalProtob\x06proto3')
)




_AGENTINFO = _descriptor.Descriptor(
  name='AgentInfo',
  full_name='AnimFireChalAgent.AgentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agents', full_name='AnimFireChalAgent.AgentInfo.agents', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=91,
)


_ACTIONINFO = _descriptor.Descriptor(
  name='ActionInfo',
  full_name='AnimFireChalAgent.ActionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions', full_name='AnimFireChalAgent.ActionInfo.actions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=149,
)


_AGENT = _descriptor.Descriptor(
  name='Agent',
  full_name='AnimFireChalAgent.Agent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='AnimFireChalAgent.Agent.agent_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='AnimFireChalAgent.Agent.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AnimFireChalAgent.Agent.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='water', full_name='AnimFireChalAgent.Agent.water', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hp', full_name='AnimFireChalAgent.Agent.hp', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idle', full_name='AnimFireChalAgent.Agent.idle', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=239,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='AnimFireChalAgent.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='AnimFireChalAgent.Action.agent_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='building_id', full_name='AnimFireChalAgent.Action.building_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=288,
)

_AGENTINFO.fields_by_name['agents'].message_type = _AGENT
_ACTIONINFO.fields_by_name['actions'].message_type = _ACTION
DESCRIPTOR.message_types_by_name['AgentInfo'] = _AGENTINFO
DESCRIPTOR.message_types_by_name['ActionInfo'] = _ACTIONINFO
DESCRIPTOR.message_types_by_name['Agent'] = _AGENT
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentInfo = _reflection.GeneratedProtocolMessageType('AgentInfo', (_message.Message,), {
  'DESCRIPTOR' : _AGENTINFO,
  '__module__' : 'AgentInfo_pb2'
  # @@protoc_insertion_point(class_scope:AnimFireChalAgent.AgentInfo)
  })
_sym_db.RegisterMessage(AgentInfo)

ActionInfo = _reflection.GeneratedProtocolMessageType('ActionInfo', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONINFO,
  '__module__' : 'AgentInfo_pb2'
  # @@protoc_insertion_point(class_scope:AnimFireChalAgent.ActionInfo)
  })
_sym_db.RegisterMessage(ActionInfo)

Agent = _reflection.GeneratedProtocolMessageType('Agent', (_message.Message,), {
  'DESCRIPTOR' : _AGENT,
  '__module__' : 'AgentInfo_pb2'
  # @@protoc_insertion_point(class_scope:AnimFireChalAgent.Agent)
  })
_sym_db.RegisterMessage(Agent)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'AgentInfo_pb2'
  # @@protoc_insertion_point(class_scope:AnimFireChalAgent.Action)
  })
_sym_db.RegisterMessage(Action)


DESCRIPTOR._options = None

_ANIMFIRECHALAGENT = _descriptor.ServiceDescriptor(
  name='AnimFireChalAgent',
  full_name='AnimFireChalAgent.AnimFireChalAgent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=290,
  serialized_end=388,
  methods=[
  _descriptor.MethodDescriptor(
    name='getAgentInfo',
    full_name='AnimFireChalAgent.AnimFireChalAgent.getAgentInfo',
    index=0,
    containing_service=None,
    input_type=_ACTIONINFO,
    output_type=_AGENTINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANIMFIRECHALAGENT)

DESCRIPTOR.services_by_name['AnimFireChalAgent'] = _ANIMFIRECHALAGENT

# @@protoc_insertion_point(module_scope)
