# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import AgentInfo_pb2 as AgentInfo__pb2


class AnimFireChalAgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getAgentInfo = channel.unary_unary(
        '/AnimFireChalAgent.AnimFireChalAgent/getAgentInfo',
        request_serializer=AgentInfo__pb2.ActionInfo.SerializeToString,
        response_deserializer=AgentInfo__pb2.AgentInfo.FromString,
        )


class AnimFireChalAgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getAgentInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnimFireChalAgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getAgentInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getAgentInfo,
          request_deserializer=AgentInfo__pb2.ActionInfo.FromString,
          response_serializer=AgentInfo__pb2.AgentInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AnimFireChalAgent.AnimFireChalAgent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
