# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import BuildingInfo_pb2 as BuildingInfo__pb2


class AnimFireChalBuildingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getBuildingInfo = channel.unary_unary(
        '/AnimFireChalBuilding.AnimFireChalBuilding/getBuildingInfo',
        request_serializer=BuildingInfo__pb2.Empty.SerializeToString,
        response_deserializer=BuildingInfo__pb2.BuildingInfo.FromString,
        )
    self.getRewards = channel.unary_unary(
        '/AnimFireChalBuilding.AnimFireChalBuilding/getRewards',
        request_serializer=BuildingInfo__pb2.Empty.SerializeToString,
        response_deserializer=BuildingInfo__pb2.Reward.FromString,
        )


class AnimFireChalBuildingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getBuildingInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getRewards(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnimFireChalBuildingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getBuildingInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getBuildingInfo,
          request_deserializer=BuildingInfo__pb2.Empty.FromString,
          response_serializer=BuildingInfo__pb2.BuildingInfo.SerializeToString,
      ),
      'getRewards': grpc.unary_unary_rpc_method_handler(
          servicer.getRewards,
          request_deserializer=BuildingInfo__pb2.Empty.FromString,
          response_serializer=BuildingInfo__pb2.Reward.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AnimFireChalBuilding.AnimFireChalBuilding', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
