package AnimFireChalServer;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingInfo.proto



public final class AnimFireChalServerProto {
  private AnimFireChalServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuildingInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AnimFireChalServer.BuildingInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    java.util.List<AnimFireChalServerProto.Building> 
        getBuildingsList();
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    AnimFireChalServerProto.Building getBuildings(int index);
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    int getBuildingsCount();
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    java.util.List<? extends AnimFireChalServerProto.BuildingOrBuilder> 
        getBuildingsOrBuilderList();
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    AnimFireChalServerProto.BuildingOrBuilder getBuildingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AnimFireChalServer.BuildingInfo}
   */
  public  static final class BuildingInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AnimFireChalServer.BuildingInfo)
      BuildingInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BuildingInfo.newBuilder() to construct.
    private BuildingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BuildingInfo() {
      buildings_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BuildingInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BuildingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                buildings_ = new java.util.ArrayList<AnimFireChalServerProto.Building>();
                mutable_bitField0_ |= 0x00000001;
              }
              buildings_.add(
                  input.readMessage(AnimFireChalServerProto.Building.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          buildings_ = java.util.Collections.unmodifiableList(buildings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnimFireChalServerProto.internal_static_AnimFireChalServer_BuildingInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnimFireChalServerProto.internal_static_AnimFireChalServer_BuildingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnimFireChalServerProto.BuildingInfo.class, AnimFireChalServerProto.BuildingInfo.Builder.class);
    }

    public static final int BUILDINGS_FIELD_NUMBER = 1;
    private java.util.List<AnimFireChalServerProto.Building> buildings_;
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    public java.util.List<AnimFireChalServerProto.Building> getBuildingsList() {
      return buildings_;
    }
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    public java.util.List<? extends AnimFireChalServerProto.BuildingOrBuilder> 
        getBuildingsOrBuilderList() {
      return buildings_;
    }
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    public int getBuildingsCount() {
      return buildings_.size();
    }
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    public AnimFireChalServerProto.Building getBuildings(int index) {
      return buildings_.get(index);
    }
    /**
     * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
     */
    public AnimFireChalServerProto.BuildingOrBuilder getBuildingsOrBuilder(
        int index) {
      return buildings_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < buildings_.size(); i++) {
        output.writeMessage(1, buildings_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < buildings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, buildings_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AnimFireChalServerProto.BuildingInfo)) {
        return super.equals(obj);
      }
      AnimFireChalServerProto.BuildingInfo other = (AnimFireChalServerProto.BuildingInfo) obj;

      if (!getBuildingsList()
          .equals(other.getBuildingsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBuildingsCount() > 0) {
        hash = (37 * hash) + BUILDINGS_FIELD_NUMBER;
        hash = (53 * hash) + getBuildingsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AnimFireChalServerProto.BuildingInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimFireChalServerProto.BuildingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.BuildingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.BuildingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AnimFireChalServerProto.BuildingInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnimFireChalServer.BuildingInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AnimFireChalServer.BuildingInfo)
        AnimFireChalServerProto.BuildingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_BuildingInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_BuildingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AnimFireChalServerProto.BuildingInfo.class, AnimFireChalServerProto.BuildingInfo.Builder.class);
      }

      // Construct using AnimFireChalServerProto.BuildingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBuildingsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (buildingsBuilder_ == null) {
          buildings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          buildingsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_BuildingInfo_descriptor;
      }

      @java.lang.Override
      public AnimFireChalServerProto.BuildingInfo getDefaultInstanceForType() {
        return AnimFireChalServerProto.BuildingInfo.getDefaultInstance();
      }

      @java.lang.Override
      public AnimFireChalServerProto.BuildingInfo build() {
        AnimFireChalServerProto.BuildingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AnimFireChalServerProto.BuildingInfo buildPartial() {
        AnimFireChalServerProto.BuildingInfo result = new AnimFireChalServerProto.BuildingInfo(this);
        int from_bitField0_ = bitField0_;
        if (buildingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            buildings_ = java.util.Collections.unmodifiableList(buildings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.buildings_ = buildings_;
        } else {
          result.buildings_ = buildingsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AnimFireChalServerProto.BuildingInfo) {
          return mergeFrom((AnimFireChalServerProto.BuildingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AnimFireChalServerProto.BuildingInfo other) {
        if (other == AnimFireChalServerProto.BuildingInfo.getDefaultInstance()) return this;
        if (buildingsBuilder_ == null) {
          if (!other.buildings_.isEmpty()) {
            if (buildings_.isEmpty()) {
              buildings_ = other.buildings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBuildingsIsMutable();
              buildings_.addAll(other.buildings_);
            }
            onChanged();
          }
        } else {
          if (!other.buildings_.isEmpty()) {
            if (buildingsBuilder_.isEmpty()) {
              buildingsBuilder_.dispose();
              buildingsBuilder_ = null;
              buildings_ = other.buildings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              buildingsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBuildingsFieldBuilder() : null;
            } else {
              buildingsBuilder_.addAllMessages(other.buildings_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AnimFireChalServerProto.BuildingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AnimFireChalServerProto.BuildingInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<AnimFireChalServerProto.Building> buildings_ =
        java.util.Collections.emptyList();
      private void ensureBuildingsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          buildings_ = new java.util.ArrayList<AnimFireChalServerProto.Building>(buildings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AnimFireChalServerProto.Building, AnimFireChalServerProto.Building.Builder, AnimFireChalServerProto.BuildingOrBuilder> buildingsBuilder_;

      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public java.util.List<AnimFireChalServerProto.Building> getBuildingsList() {
        if (buildingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(buildings_);
        } else {
          return buildingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public int getBuildingsCount() {
        if (buildingsBuilder_ == null) {
          return buildings_.size();
        } else {
          return buildingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public AnimFireChalServerProto.Building getBuildings(int index) {
        if (buildingsBuilder_ == null) {
          return buildings_.get(index);
        } else {
          return buildingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder setBuildings(
          int index, AnimFireChalServerProto.Building value) {
        if (buildingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildingsIsMutable();
          buildings_.set(index, value);
          onChanged();
        } else {
          buildingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder setBuildings(
          int index, AnimFireChalServerProto.Building.Builder builderForValue) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          buildings_.set(index, builderForValue.build());
          onChanged();
        } else {
          buildingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder addBuildings(AnimFireChalServerProto.Building value) {
        if (buildingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildingsIsMutable();
          buildings_.add(value);
          onChanged();
        } else {
          buildingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder addBuildings(
          int index, AnimFireChalServerProto.Building value) {
        if (buildingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuildingsIsMutable();
          buildings_.add(index, value);
          onChanged();
        } else {
          buildingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder addBuildings(
          AnimFireChalServerProto.Building.Builder builderForValue) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          buildings_.add(builderForValue.build());
          onChanged();
        } else {
          buildingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder addBuildings(
          int index, AnimFireChalServerProto.Building.Builder builderForValue) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          buildings_.add(index, builderForValue.build());
          onChanged();
        } else {
          buildingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder addAllBuildings(
          java.lang.Iterable<? extends AnimFireChalServerProto.Building> values) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, buildings_);
          onChanged();
        } else {
          buildingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder clearBuildings() {
        if (buildingsBuilder_ == null) {
          buildings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          buildingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public Builder removeBuildings(int index) {
        if (buildingsBuilder_ == null) {
          ensureBuildingsIsMutable();
          buildings_.remove(index);
          onChanged();
        } else {
          buildingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public AnimFireChalServerProto.Building.Builder getBuildingsBuilder(
          int index) {
        return getBuildingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public AnimFireChalServerProto.BuildingOrBuilder getBuildingsOrBuilder(
          int index) {
        if (buildingsBuilder_ == null) {
          return buildings_.get(index);  } else {
          return buildingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public java.util.List<? extends AnimFireChalServerProto.BuildingOrBuilder> 
           getBuildingsOrBuilderList() {
        if (buildingsBuilder_ != null) {
          return buildingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(buildings_);
        }
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public AnimFireChalServerProto.Building.Builder addBuildingsBuilder() {
        return getBuildingsFieldBuilder().addBuilder(
            AnimFireChalServerProto.Building.getDefaultInstance());
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public AnimFireChalServerProto.Building.Builder addBuildingsBuilder(
          int index) {
        return getBuildingsFieldBuilder().addBuilder(
            index, AnimFireChalServerProto.Building.getDefaultInstance());
      }
      /**
       * <code>repeated .AnimFireChalServer.Building buildings = 1;</code>
       */
      public java.util.List<AnimFireChalServerProto.Building.Builder> 
           getBuildingsBuilderList() {
        return getBuildingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AnimFireChalServerProto.Building, AnimFireChalServerProto.Building.Builder, AnimFireChalServerProto.BuildingOrBuilder> 
          getBuildingsFieldBuilder() {
        if (buildingsBuilder_ == null) {
          buildingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AnimFireChalServerProto.Building, AnimFireChalServerProto.Building.Builder, AnimFireChalServerProto.BuildingOrBuilder>(
                  buildings_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          buildings_ = null;
        }
        return buildingsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AnimFireChalServer.BuildingInfo)
    }

    // @@protoc_insertion_point(class_scope:AnimFireChalServer.BuildingInfo)
    private static final AnimFireChalServerProto.BuildingInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AnimFireChalServerProto.BuildingInfo();
    }

    public static AnimFireChalServerProto.BuildingInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuildingInfo>
        PARSER = new com.google.protobuf.AbstractParser<BuildingInfo>() {
      @java.lang.Override
      public BuildingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuildingInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BuildingInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuildingInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AnimFireChalServerProto.BuildingInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuildingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AnimFireChalServer.Building)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 building_id = 1;</code>
     * @return The buildingId.
     */
    int getBuildingId();

    /**
     * <code>int32 fieryness = 2;</code>
     * @return The fieryness.
     */
    int getFieryness();

    /**
     * <code>double temperature = 3;</code>
     * @return The temperature.
     */
    double getTemperature();
  }
  /**
   * Protobuf type {@code AnimFireChalServer.Building}
   */
  public  static final class Building extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AnimFireChalServer.Building)
      BuildingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Building.newBuilder() to construct.
    private Building(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Building() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Building();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Building(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              buildingId_ = input.readInt32();
              break;
            }
            case 16: {

              fieryness_ = input.readInt32();
              break;
            }
            case 25: {

              temperature_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnimFireChalServerProto.internal_static_AnimFireChalServer_Building_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnimFireChalServerProto.internal_static_AnimFireChalServer_Building_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnimFireChalServerProto.Building.class, AnimFireChalServerProto.Building.Builder.class);
    }

    public static final int BUILDING_ID_FIELD_NUMBER = 1;
    private int buildingId_;
    /**
     * <code>int32 building_id = 1;</code>
     * @return The buildingId.
     */
    public int getBuildingId() {
      return buildingId_;
    }

    public static final int FIERYNESS_FIELD_NUMBER = 2;
    private int fieryness_;
    /**
     * <code>int32 fieryness = 2;</code>
     * @return The fieryness.
     */
    public int getFieryness() {
      return fieryness_;
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 3;
    private double temperature_;
    /**
     * <code>double temperature = 3;</code>
     * @return The temperature.
     */
    public double getTemperature() {
      return temperature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (buildingId_ != 0) {
        output.writeInt32(1, buildingId_);
      }
      if (fieryness_ != 0) {
        output.writeInt32(2, fieryness_);
      }
      if (temperature_ != 0D) {
        output.writeDouble(3, temperature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (buildingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, buildingId_);
      }
      if (fieryness_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fieryness_);
      }
      if (temperature_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, temperature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AnimFireChalServerProto.Building)) {
        return super.equals(obj);
      }
      AnimFireChalServerProto.Building other = (AnimFireChalServerProto.Building) obj;

      if (getBuildingId()
          != other.getBuildingId()) return false;
      if (getFieryness()
          != other.getFieryness()) return false;
      if (java.lang.Double.doubleToLongBits(getTemperature())
          != java.lang.Double.doubleToLongBits(
              other.getTemperature())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDING_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingId();
      hash = (37 * hash) + FIERYNESS_FIELD_NUMBER;
      hash = (53 * hash) + getFieryness();
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTemperature()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AnimFireChalServerProto.Building parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Building parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Building parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Building parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Building parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Building parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Building parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Building parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimFireChalServerProto.Building parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Building parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimFireChalServerProto.Building parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Building parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AnimFireChalServerProto.Building prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnimFireChalServer.Building}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AnimFireChalServer.Building)
        AnimFireChalServerProto.BuildingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Building_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Building_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AnimFireChalServerProto.Building.class, AnimFireChalServerProto.Building.Builder.class);
      }

      // Construct using AnimFireChalServerProto.Building.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        buildingId_ = 0;

        fieryness_ = 0;

        temperature_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Building_descriptor;
      }

      @java.lang.Override
      public AnimFireChalServerProto.Building getDefaultInstanceForType() {
        return AnimFireChalServerProto.Building.getDefaultInstance();
      }

      @java.lang.Override
      public AnimFireChalServerProto.Building build() {
        AnimFireChalServerProto.Building result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AnimFireChalServerProto.Building buildPartial() {
        AnimFireChalServerProto.Building result = new AnimFireChalServerProto.Building(this);
        result.buildingId_ = buildingId_;
        result.fieryness_ = fieryness_;
        result.temperature_ = temperature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AnimFireChalServerProto.Building) {
          return mergeFrom((AnimFireChalServerProto.Building)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AnimFireChalServerProto.Building other) {
        if (other == AnimFireChalServerProto.Building.getDefaultInstance()) return this;
        if (other.getBuildingId() != 0) {
          setBuildingId(other.getBuildingId());
        }
        if (other.getFieryness() != 0) {
          setFieryness(other.getFieryness());
        }
        if (other.getTemperature() != 0D) {
          setTemperature(other.getTemperature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AnimFireChalServerProto.Building parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AnimFireChalServerProto.Building) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int buildingId_ ;
      /**
       * <code>int32 building_id = 1;</code>
       * @return The buildingId.
       */
      public int getBuildingId() {
        return buildingId_;
      }
      /**
       * <code>int32 building_id = 1;</code>
       * @param value The buildingId to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingId(int value) {
        
        buildingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 building_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingId() {
        
        buildingId_ = 0;
        onChanged();
        return this;
      }

      private int fieryness_ ;
      /**
       * <code>int32 fieryness = 2;</code>
       * @return The fieryness.
       */
      public int getFieryness() {
        return fieryness_;
      }
      /**
       * <code>int32 fieryness = 2;</code>
       * @param value The fieryness to set.
       * @return This builder for chaining.
       */
      public Builder setFieryness(int value) {
        
        fieryness_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fieryness = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFieryness() {
        
        fieryness_ = 0;
        onChanged();
        return this;
      }

      private double temperature_ ;
      /**
       * <code>double temperature = 3;</code>
       * @return The temperature.
       */
      public double getTemperature() {
        return temperature_;
      }
      /**
       * <code>double temperature = 3;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(double value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double temperature = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        
        temperature_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AnimFireChalServer.Building)
    }

    // @@protoc_insertion_point(class_scope:AnimFireChalServer.Building)
    private static final AnimFireChalServerProto.Building DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AnimFireChalServerProto.Building();
    }

    public static AnimFireChalServerProto.Building getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Building>
        PARSER = new com.google.protobuf.AbstractParser<Building>() {
      @java.lang.Override
      public Building parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Building(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Building> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Building> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AnimFireChalServerProto.Building getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AnimFireChalServer.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code AnimFireChalServer.Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AnimFireChalServer.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnimFireChalServerProto.internal_static_AnimFireChalServer_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnimFireChalServerProto.internal_static_AnimFireChalServer_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnimFireChalServerProto.Empty.class, AnimFireChalServerProto.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AnimFireChalServerProto.Empty)) {
        return super.equals(obj);
      }
      AnimFireChalServerProto.Empty other = (AnimFireChalServerProto.Empty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AnimFireChalServerProto.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimFireChalServerProto.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimFireChalServerProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AnimFireChalServerProto.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnimFireChalServer.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AnimFireChalServer.Empty)
        AnimFireChalServerProto.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AnimFireChalServerProto.Empty.class, AnimFireChalServerProto.Empty.Builder.class);
      }

      // Construct using AnimFireChalServerProto.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Empty_descriptor;
      }

      @java.lang.Override
      public AnimFireChalServerProto.Empty getDefaultInstanceForType() {
        return AnimFireChalServerProto.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public AnimFireChalServerProto.Empty build() {
        AnimFireChalServerProto.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AnimFireChalServerProto.Empty buildPartial() {
        AnimFireChalServerProto.Empty result = new AnimFireChalServerProto.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AnimFireChalServerProto.Empty) {
          return mergeFrom((AnimFireChalServerProto.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AnimFireChalServerProto.Empty other) {
        if (other == AnimFireChalServerProto.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AnimFireChalServerProto.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AnimFireChalServerProto.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AnimFireChalServer.Empty)
    }

    // @@protoc_insertion_point(class_scope:AnimFireChalServer.Empty)
    private static final AnimFireChalServerProto.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AnimFireChalServerProto.Empty();
    }

    public static AnimFireChalServerProto.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AnimFireChalServerProto.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RewardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AnimFireChalServer.Reward)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 reward = 1;</code>
     * @return The reward.
     */
    int getReward();
  }
  /**
   * Protobuf type {@code AnimFireChalServer.Reward}
   */
  public  static final class Reward extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AnimFireChalServer.Reward)
      RewardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Reward.newBuilder() to construct.
    private Reward(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reward() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Reward();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Reward(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              reward_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnimFireChalServerProto.internal_static_AnimFireChalServer_Reward_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnimFireChalServerProto.internal_static_AnimFireChalServer_Reward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnimFireChalServerProto.Reward.class, AnimFireChalServerProto.Reward.Builder.class);
    }

    public static final int REWARD_FIELD_NUMBER = 1;
    private int reward_;
    /**
     * <code>int32 reward = 1;</code>
     * @return The reward.
     */
    public int getReward() {
      return reward_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reward_ != 0) {
        output.writeInt32(1, reward_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reward_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reward_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AnimFireChalServerProto.Reward)) {
        return super.equals(obj);
      }
      AnimFireChalServerProto.Reward other = (AnimFireChalServerProto.Reward) obj;

      if (getReward()
          != other.getReward()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REWARD_FIELD_NUMBER;
      hash = (53 * hash) + getReward();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AnimFireChalServerProto.Reward parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Reward parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Reward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Reward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Reward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimFireChalServerProto.Reward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimFireChalServerProto.Reward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Reward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimFireChalServerProto.Reward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Reward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimFireChalServerProto.Reward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimFireChalServerProto.Reward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AnimFireChalServerProto.Reward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnimFireChalServer.Reward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AnimFireChalServer.Reward)
        AnimFireChalServerProto.RewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Reward_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Reward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AnimFireChalServerProto.Reward.class, AnimFireChalServerProto.Reward.Builder.class);
      }

      // Construct using AnimFireChalServerProto.Reward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        reward_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnimFireChalServerProto.internal_static_AnimFireChalServer_Reward_descriptor;
      }

      @java.lang.Override
      public AnimFireChalServerProto.Reward getDefaultInstanceForType() {
        return AnimFireChalServerProto.Reward.getDefaultInstance();
      }

      @java.lang.Override
      public AnimFireChalServerProto.Reward build() {
        AnimFireChalServerProto.Reward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AnimFireChalServerProto.Reward buildPartial() {
        AnimFireChalServerProto.Reward result = new AnimFireChalServerProto.Reward(this);
        result.reward_ = reward_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AnimFireChalServerProto.Reward) {
          return mergeFrom((AnimFireChalServerProto.Reward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AnimFireChalServerProto.Reward other) {
        if (other == AnimFireChalServerProto.Reward.getDefaultInstance()) return this;
        if (other.getReward() != 0) {
          setReward(other.getReward());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AnimFireChalServerProto.Reward parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AnimFireChalServerProto.Reward) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int reward_ ;
      /**
       * <code>int32 reward = 1;</code>
       * @return The reward.
       */
      public int getReward() {
        return reward_;
      }
      /**
       * <code>int32 reward = 1;</code>
       * @param value The reward to set.
       * @return This builder for chaining.
       */
      public Builder setReward(int value) {
        
        reward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reward = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReward() {
        
        reward_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AnimFireChalServer.Reward)
    }

    // @@protoc_insertion_point(class_scope:AnimFireChalServer.Reward)
    private static final AnimFireChalServerProto.Reward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AnimFireChalServerProto.Reward();
    }

    public static AnimFireChalServerProto.Reward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Reward>
        PARSER = new com.google.protobuf.AbstractParser<Reward>() {
      @java.lang.Override
      public Reward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reward(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reward> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reward> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AnimFireChalServerProto.Reward getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimFireChalServer_BuildingInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimFireChalServer_BuildingInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimFireChalServer_Building_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimFireChalServer_Building_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimFireChalServer_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimFireChalServer_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimFireChalServer_Reward_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimFireChalServer_Reward_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BuildingInfo.proto\022\022AnimFireChalServer" +
      "\"?\n\014BuildingInfo\022/\n\tbuildings\030\001 \003(\0132\034.An" +
      "imFireChalServer.Building\"G\n\010Building\022\023\n" +
      "\013building_id\030\001 \001(\005\022\021\n\tfieryness\030\002 \001(\005\022\023\n" +
      "\013temperature\030\003 \001(\001\"\007\n\005Empty\"\030\n\006Reward\022\016\n" +
      "\006reward\030\001 \001(\0052\254\001\n\022AnimFireChalServer\022P\n\017" +
      "getBuildingInfo\022\031.AnimFireChalServer.Emp" +
      "ty\032 .AnimFireChalServer.BuildingInfo\"\000\022D" +
      "\n\tgetReward\022\031.AnimFireChalServer.Empty\032\032" +
      ".AnimFireChalServer.Reward\"\000B-\n\022AnimFire" +
      "ChalServerB\027AnimFireChalServerProtob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AnimFireChalServer_BuildingInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnimFireChalServer_BuildingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimFireChalServer_BuildingInfo_descriptor,
        new java.lang.String[] { "Buildings", });
    internal_static_AnimFireChalServer_Building_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnimFireChalServer_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimFireChalServer_Building_descriptor,
        new java.lang.String[] { "BuildingId", "Fieryness", "Temperature", });
    internal_static_AnimFireChalServer_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AnimFireChalServer_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimFireChalServer_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_AnimFireChalServer_Reward_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AnimFireChalServer_Reward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimFireChalServer_Reward_descriptor,
        new java.lang.String[] { "Reward", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
